CREATE TABLE IF NOT EXSIST User {
    user_id LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL, Unique
    produced integer NOT NULL,
    date_prod date,
    kind varchar(10),
    len_min integer
}