CREATE TABLE IF NOT EXISTS "Users"
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255) NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS "AgeRating"
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age_rating  VARCHAR(25)  NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Genre"
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Films"
(
    film_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL,
    description   VARCHAR(200) NOT NULL,
    release_date  DATE         NOT NULL,
    duration      INT          NOT NULL,
    age_rating_id INT          NOT NULL,
    FOREIGN KEY (age_rating_id) REFERENCES "AgeRating" (id)
);

CREATE TABLE IF NOT EXISTS "FilmGenre"
(
    film_id  BIGINT,
    genre_id INT,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES "Films" (film_id),
    FOREIGN KEY (genre_id) REFERENCES "Genre" (id)
);

CREATE TABLE IF NOT EXISTS "FavoriteFilms"
(
    user_id BIGINT,
    film_id BIGINT,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES "Users" (user_id),
    FOREIGN KEY (film_id) REFERENCES "Films" (film_id)
);

CREATE TABLE IF NOT EXISTS "FriendshipStatus"
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Friendship"
(
    from_user_id         BIGINT,
    to_user_id           BIGINT,
    friendship_status_id INT NOT NULL,
    PRIMARY KEY (from_user_id, to_user_id),
    FOREIGN KEY (from_user_id) REFERENCES "Users" (user_id),
    FOREIGN KEY (to_user_id) REFERENCES "Users" (user_id),
    FOREIGN KEY (friendship_status_id) REFERENCES "FriendshipStatus" (id)
);

CREATE TABLE IF NOT EXISTS "IncomingRequestToFriends"
(
    user_id      BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, from_user_id),
    FOREIGN KEY (user_id) REFERENCES "Users" (user_id),
    FOREIGN KEY (from_user_id) REFERENCES "Users" (user_id)
);